#自动调用api保活，模仿人为开发版
name: Auto Api SR

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "38 2,5,8 * * 1-5"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install requests
        pip install fake-useragent
    - name: Read config from secrets  #读取机密
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }} # secrets_id 提供
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }} # secrets_key 提供
      run: | 
        echo $CONFIG_ID > configid.txt
        echo $CONFIG_KEY > configkey.txt
        sed -i '17 r configid.txt' gvjyxrjff645FFFAjksvj.py
        sed -i '18 r configkey.txt' gvjyxrjff645FFFAjksvj.py
    - name: Test Api #Api调用
      run: | 
        python gvjyxrjff645FFFAjksvj.py
